//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniverisParser.ParserLibrary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ParserResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ParserResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UniverisParser.ParserLibrary.ParserResources", typeof(ParserResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DXCallbackName=MarkJournalPivotGrid&amp;__DXCallbackArgument=c0%3AC%7C&amp;MarkJournalPivotGrid=%7B%26quot%3BcallbackState%26quot%3B%3A%26quot%3BFLDS_CBDEL_Bg2832ZpYCY0cJo0SnjTrdr%2FWrtoTMlWnbpRAcH0smK6e92xQvMYo9cmthYZKJ1UUbzCFv%2FQdk0H1AK8uyp3UOL%2BtS%2F9AlrFuRtUZUojhfFkk%2F6jHr3x%2BJlxHzWiLZ9TWJyubmoIXKe8UaNnLQ7QbD%2BuYLddDcvHCTLGss72sHbXLHnUW9x%2BouRK4NgGVEAsBFD%2BU6t4BAssPhaz5ShOUfwsUyG6bk8YoOL6YSVAGE3SPxG4Tn0fztHxFCo4i3wBl7%2FSQjEiSoAcw0lgGF2y7uToHRG8G4s3rmf9pZFC5tebpBln1JjkiRmUD6wCnCWY6gHMcdIZYMmhCsdx0de1GlIg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JournalString {
            get {
                return ResourceManager.GetString("JournalString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __RequestVerificationToken={0}&amp;UserName={1}&amp;dxPassword={2}&amp;LoginBtn=%D0%92%D1%85%D0%BE%D0%B4&amp;CurrentLang%24State=%7B%26quot%3BvalidationState%26quot%3B%3A%26quot%3B%26quot%3B%7D&amp;CurrentLang_VI=ru&amp;CurrentLang=%D0%A0%D1%83%D1%81%D1%81%D0%BA%D0%B8%D0%B9&amp;CurrentLang%24DDDState=%7B%26quot%3BwindowsState%26quot%3B%3A%26quot%3B0%3A0%3A-1%3A0%3A0%3A0%3A-10000%3A-10000%3A1%3A0%3A0%3A0%26quot%3B%7D&amp;CurrentLang%24DDD%24L%24State=%7B%26quot%3BCustomCallback%26quot%3B%3A%26quot%3B%26quot%3B%7D&amp;CurrentLang%24DDD%24L=ru&amp;D [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NavMenuString {
            get {
                return ResourceManager.GetString("NavMenuString", resourceCulture);
            }
        }
    }
}
